/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity list */
        get: operations["getActivities"];
        put?: never;
        /** Create new activity */
        post: operations["createActivity"];
        /** Batch delete activities */
        delete: operations["batchDeleteActivities"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest activity by types */
        get: operations["getLatestActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single activity */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        /** Delete activity */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        /** Update activity */
        patch: operations["updateActivity"];
        trace?: never;
    };
    "/activities/upload-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload activity photo */
        post: operations["uploadActivityPhoto"];
        /** Delete activity photo */
        delete: operations["deleteActivityPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse voice input and create activity
         * @description Accepts natural language text (from voice input) and uses AI to parse it into a structured activity record.
         *     Supports Chinese input like "宝宝喝了80毫升奶" or "刚换了尿布，有便便".
         */
        post: operations["parseVoiceInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baby-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get baby profile */
        get: operations["getBabyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update baby profile */
        patch: operations["updateBabyProfile"];
        trace?: never;
    };
    "/baby-profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload baby avatar */
        post: operations["uploadAvatar"];
        /** Delete baby avatar */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityType: "SLEEP" | "DIAPER" | "BREASTFEED" | "BOTTLE" | "HEAD_LIFT" | "PASSIVE_EXERCISE" | "GAS_EXERCISE" | "BATH" | "OUTDOOR" | "EARLY_EDUCATION";
        /** @enum {string} */
        PoopColor: "YELLOW" | "GREEN" | "BROWN" | "BLACK" | "WHITE" | "RED";
        /** @enum {string} */
        PeeAmount: "SMALL" | "MEDIUM" | "LARGE";
        Activity: {
            id: string;
            type: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime: string;
            /**
             * Format: date-time
             * @description 活动结束时间（正在进行的活动没有结束时间）
             */
            endTime?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            hasPoop?: boolean | null;
            hasPee?: boolean | null;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string | null;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean | null;
            milkAmount?: number | null;
            notes?: string | null;
        };
        CreateActivityInput: {
            type: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime: string;
            /**
             * Format: date-time
             * @description 活动结束时间（可选）
             */
            endTime?: string;
            hasPoop?: boolean;
            hasPee?: boolean;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean;
            milkAmount?: number;
            notes?: string;
        };
        UpdateActivityInput: {
            type?: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime?: string;
            /**
             * Format: date-time
             * @description 活动结束时间
             */
            endTime?: string;
            hasPoop?: boolean;
            hasPee?: boolean;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean;
            milkAmount?: number;
            notes?: string;
        };
        BabyProfile: {
            id: string;
            name?: string | null;
            avatarUrl?: string | null;
            /** Format: date-time */
            birthDate?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateBabyProfileInput: {
            name?: string;
            avatarUrl?: string;
            /** Format: date-time */
            birthDate?: string;
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description Server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getActivities: {
        parameters: {
            query?: {
                limit?: number;
                type?: components["schemas"]["ActivityType"];
                /** @description Comma-separated list of activity types to filter */
                types?: string;
                /** @description Date in YYYY-MM-DD format */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityInput"];
            };
        };
        responses: {
            /** @description Created activity */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    batchDeleteActivities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        count?: number;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getLatestActivity: {
        parameters: {
            query: {
                /** @description Comma-separated list of activity types */
                types: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest activity (null if not found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"] | null;
                };
            };
            /** @description Bad request - types parameter required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityInput"];
            };
        };
        responses: {
            /** @description Updated activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    uploadActivityPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    category?: string;
                };
            };
        };
        responses: {
            /** @description Upload success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteActivityPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    url: string;
                };
            };
        };
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    parseVoiceInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The voice input text to parse
                     * @example 宝宝刚才喝了60毫升奶
                     */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Activity created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        activity?: components["schemas"]["Activity"];
                        parsed?: {
                            /** @description AI confidence level (0-1) */
                            confidence?: number;
                            originalText?: string;
                        };
                        /** @description Human-readable confirmation message */
                        message?: string;
                    };
                };
            };
            /** @description Parse failed or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        /** @enum {string} */
                        code?: "MISSING_TEXT" | "PARSE_FAILED" | "INVALID_TYPE";
                        originalText?: string;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getBabyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baby profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyProfile"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateBabyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBabyProfileInput"];
            };
        };
        responses: {
            /** @description Updated baby profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyProfile"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                        profile?: components["schemas"]["BabyProfile"];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
